name: AutoPush from ChatGPT

on:
  repository_dispatch:   # Déclencheur externe (moi !)
    types: [chatgpt-push]

jobs:
  autopush:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer ton repo
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      # Étape 2 : Créer/modifier le fichier envoyé par ChatGPT
      - name: Apply file changes
        run: |
          echo "${{ github.event.client_payload.content }}" > ${{ github.event.client_payload.path }}
          git config user.name "chatgpt-bot"
          git config user.email "chatgpt-bot@tinsflash.com"
          git add ${{ github.event.client_payload.path }}
          git commit -m "🤖 Auto-update by ChatGPT: ${{ github.event.client_payload.path }}" || echo "No changes to commit"
          git push origin main
