name: Auto Organize Files

on:
  push:
    branches:
      - main   # déclenche quand tu ajoutes un fichier dans main

permissions:
  contents: write

jobs:
  organize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Organize files
        run: |
          mkdir -p public services routes utils
          for f in $(ls -p | grep -v / | grep -vE '^(.gitignore|README.md)$'); do
            ext="${f##*.}"
            lower=$(echo "$f" | tr '[:upper:]' '[:lower:]')

            if [ "$ext" = "html" ] || [ "$ext" = "css" ]; then
              mv "$f" public/ || true
            elif [ "$ext" = "js" ]; then
              if [[ "$lower" == *service* || "$lower" == *engine* ]]; then
                mv "$f" services/ || true
              elif [[ "$lower" == *route* ]]; then
                mv "$f" routes/ || true
              else
                mv "$f" utils/ || true
              fi
            fi
          done

      - name: Commit & Push changes
        run: |
          git config user.name "autopush-bot"
          git config user.email "autopush-bot@users.noreply.github.com"
          git add .
          git commit -m "Auto organize files" || echo "No changes"
          git push origin main
