name: Auto Push Full Repo

on:
  schedule:
    - cron: "*/5 * * * *" # toutes les 5 minutes
  workflow_dispatch: # déclenchement manuel possible

jobs:
  autopush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Commit & Push all changes
        run: |
          git config --global user.name "tinsflash-bot"
          git config --global user.email "bot@tinsflash.com"

          git add -A
          git commit -m "🔄 Auto-sync full repo (backend + frontend)" || echo "No changes to commit"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
