name: Auto Commit to GitHub

on:
  workflow_dispatch:   # lancement manuel
  push:
    branches:
      - main           # facultatif : peut aussi se déclencher quand tu pushes

permissions:
  contents: write      # indispensable pour autoriser le push

jobs:
  autopush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Exemple : mettre un fichier HTML corrigé dans public/
      - name: Copy generated files
        run: |
          mkdir -p public
          echo "<h1>Nouvelle version</h1>" > public/index.html
          # Ici tu remplaces par la copie réelle des fichiers générés par GPTCode

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto update via GPTCode" || echo "No changes to commit"
          git push
